<?php
return array(
    'wishlist/add/([0-9]+)' => 'basced/AddWishlistItem/$1',
    'basced/add/([0-9]+)' => 'basced/AddBascedItem/$1',
    'basced/del/([0-9]+)' => 'basced/DeleteItem/$1',
    'wishlist/del/([0-9]+)' => 'basced/DelWishlistItem/$1',
    'wishlist/add-to-cart/([0-9]+)' => 'basced/WishlistItemAddToCart/$1',
    'basced/display/view' => 'basced/DisplayBasced',
    'index/language/([a-z]+)' => 'public/LangChange/$1',
    'basced/clear' => 'basced/ClearBasced',
    'basced/calculate' => 'basced/CalculateBasced',
    'basced/order-success' => 'basced/OrderSuccess',
    'contact/add' => 'public/ContactAdd',
    'productinfo/([0-9]+)' => 'public/Info/$1',
    'blog-detail/([0-9]+)' => 'public/BlogDetail/$1',
    'catalog/([0-9]+)' => 'public/Catalog/$1',
    'user/edit-success' => 'public/ProfileEdit',
    'user/register' => 'public/RegisterUser',
    'user/login' => 'public/LoginUser',
    'user/profile' => 'public/ProfileDisplay',
    'user/wishlist' => 'public/Wishlist',
    'user/orders' => 'public/Orders',
    'user/setting' => 'public/Setting',


    'main/user-valid' => 'public/LoginProcess',
    'support/add' => 'product/AddSupport',

    'add/comment' => 'public/AddComment',
    'item/search' => 'public/ItemSearch',
    'login-process' => 'public/LoginProcess',
    'register-process' => 'public/RegisterProcess',
    'sign-out' => 'public/SignOut',

    'login' => 'public/Login',
    'profile' => 'public/ProfileUser',
    'change-location' => 'public/ChangeLocation',

    'currier' => 'public/CurrierForm',
    'order-confirm' => 'public/CurrierForm',
    'category' => 'category/CategoryView',
    'complete-payment' => 'public/OrderSuccess',
    'payment' => 'public/OrderPayment',
    'order-complete' => 'basced/OrderComplete',
    'order-check' => 'basced/CheckOrder',
    'contact' => 'public/Contact',
    'delivery' => 'public/Delivery',
    'privacy-policy' => 'public/PrivacyPolicy',
    'index' => 'public/Index',
    'cart' => 'public/Cart',
    'password-page' => 'product/PasswordPage',
    'about' => 'public/About',
    'pages' => 'public/CreatedPages',
    'blog' => 'public/Blog',

    'order' => 'basced/OrderBasced',
    '' => 'public/Index',
);